### ISSUE TITLE
複数言語対応

### ISSUE THREAD

**Issue by clay7614** [okata-t/yt-dlp_GUI#16]
language.iniを作って、各ウィジェットのtextをiniから取得する感じ
メニューバーから言語選択出来るようにするとか
日本人以外は使わないだろうけど、テスト終わったら手を付けてみたい

**Comment by clay7614** [comment]
これ作っときます

**Comment by qyurila** [comment]
はじめまして
これが完成したら韓国語対応のPRを作ってみたいと思います
(close通知を受け取るためにコメントします)

**Comment by clay7614** [comment]
私は現在私用で忙しため、2日後の木曜日より機能作成に取り掛かる予定です。
ご協力についての連絡ありがとうございます。

**Comment by clay7614** [comment]
制作者のおかたさんに伺ったところ、余裕が出来次第取り掛かるようですので、もう少し早く実装されるかもしれないです。

**Comment by clay7614** [comment]
今作ってます
