### ISSUE TITLE
アプリ内からリリースノートを確認する機能

### ISSUE THREAD

**Issue by okata-t** [okata-t/yt-dlp_GUI#26]
バージョンごとの変更点を見れるようにしたい

**Comment by clay7614** [comment]
これ出来るかも
明日以降にやってみます

**Comment by clay7614** [comment]
releasesの中身をスクレイピングして、バージョンと変更履歴を辞書型に保存するプログラムを作成しました。
プログラムと出力結果は以下に記しておきます。
どういった形で実装するか思いつかなかったので一旦issueに投げときます。何か案があれば返事を頂けるとありがたいです。

```
import os
import requests
from packaging import version
from bs4 import BeautifulSoup

def get_release_note(url):
    #スクレイピングしたtxtの保存場所を指定
    log_file = "log.txt"

    #key→辞書型変換の際に必要な変数を定義
    Mode = 1
    value = ""
    dic = {}

    #logファイルが0バイト、またはアプデ前の状態だった場合はスクレイピングを行う
    this_version = "2.6.1"
    latest_log_version = "2.6.1"

    if os.stat(log_file).st_size == 0 or version.parse(this_version) < version.parse(latest_log_version):
        #releasesのページ数を取得
        response = requests.get(url)
        soup = BeautifulSoup(response.text, "html.parser")
        page = soup.find_all(class_="pagination")
        for page in page:
            page_num = int(page.text[-6:-5])
            break

        #log.txtの中身を0バイトにして初期化
        with open(log_file, mode="w") as f:
            f.truncate(0)

        #releasesのバージョン・変更履歴をtxtで取得
        for i in range(page_num):
            url_page_num = url + "?page=" + str(i+1)
            response = requests.get(url_page_num)
            soup = BeautifulSoup(response.text, "html.parser")
            note = soup.find_all(class_="Box-body")

            for note in note:
                # バージョンと変更履歴の要素を抽出
                versions = note.find_all(class_="Link--primary Link")
                changes = note.find_all(class_="markdown-body my-3")

                for ver in versions:
                    with open(log_file, mode='a', encoding='utf-8') as f:
                        f.write(ver.text + "\n")

                for change in changes:
                    with open(log_file, mode='a', encoding='utf-8') as f:
                        f.write(change.text + "\n")
                        f.write("\n")
                        f.write("---\n")

        #大量に付随してくる余計なヌル文字を削除。ついでに「latest」表記も削除
        with open(log_file, 'r+', encoding="UTF-8") as f:
            lines = f.readlines()
            f.seek(0)
            f.truncate()
            lines_to_delete = [5, 11]
            for i, line in enumerate(lines):
                if i not in lines_to_delete and line.strip():
                    f.write(line)

    #バージョン・変更履歴をtxtから辞書型に変換
    with open('log.txt', encoding="utf-8") as f:
        for line in f:
            if line == "---\n":
                dic[key] = value
                value = ""
                Mode = 1
            else:
                if Mode == 1:
                    key = line.strip()
                    Mode = 0
                else:
                    value += line

    return dic

if __name__ == "__main__":
    url = "https://github.com/okata-t/yt-dlp_GUI/releases"
    releases = get_release_note(url)
    print(releases)

    """
    #辞書型からの文字取り出しプログラム例
    keys = list(releases.keys())
    for i in range(len(releases)):
        key = keys[i]
        value = releases[key]
        print(keys[i] + "\n" + value)
    """
```

`{'yt-dlp_GUI v2.6.1': '修正\n動画情報取得時のエラーを修正\n', 'yt-dlp_GUI v2.6.0': '機能追加\n解像度指定機能\nダウンロード時の画質を指定することができます。「最高画質」にするとダウンロード可能な画質の中で一番大きいものになります\n', 'yt-dlp_GUI v2.5.1': '機能追加\n韓国語に対応\nqyurila さんに翻訳していただきま した。ありがとうございます！\n修正\n英語の翻訳を改善\n', 'yt-dlp_GUI v2.5.0': '機能追加\n言語設定機能\n表示言語を日本語/Englishの二つに切り替えられるように なりました\n修正\nクイックモード時に直接アプリを終了できるボタンを追加\nバージョン情報をプログラム内に記載するように変更\nテーマ保存時に再起動されない問題\n', 'yt-dlp_GUI v2.4.0': '機能追加\nクイックモード\nメニューバーの「ベータ機能」にクイックモードを追加しました\n起動するとメインウィンドウの代わりにタスクト レイに移動します\nアイコンを左クリック、または右クリック→ダウンロードでクリップボードにコピーしているリンクの動画をダウンロードします(現在制作途中なのでダウンロード進捗等はメインウィンドウに戻らないと見えません)\n修正\nダウンロード時のプログレスバーに動画のファイル名を表示するようにしました\nすでに同じファイル が存在するとエラーになります\n', 'yt-dlp_GUI v2.3.1': '修正\nyt-dlp 2024.08.06に更新したため、ニコニコ動画のダウンロードに対応しました\n動画情報取得時にCookie設定を使用できるように修正\n', 'yt-dlp_GUI v2.3.0': '機能追加\n動画の情報取得機能\n動画のタイトル、サムネイル、再生時間を表示することができます\n時間範囲 指定ダウンロード\n動画をダウンロードする範囲を指定することができます(動画によっては音声だけになります)\n修正\nテーマエディタの挙動を修正\nwebmを選択したときにサムネイル埋め込みを設定できないように修正\n', 'yt-dlp_GUI v2.2.2': '修正\nconfig.iniの読み込み方法を改善（アップデート時のバグを修正）\nリンクを開くにTwitchを追加\n', 'yt-dlp_GUI v2.2.1': '修正\n前バージョンからアップデートすると起動できない問題\n', 'yt-dlp_GUI v2.2.0': '機能追加\n動画の拡張子選択機能\nmp4、webmから選択できます\nwebmを選択しダウンロードできなかった場合はmp4をwebmに変換します(時間がかかる)\nCookie情報読み込み設定\nメニューバーよりCookieを取得す るブラウザを設定できます\n例えば、YouTubeにログインしているブラウザを選択した場合、自分が入っているメンバーシップ限定動画をダウンロードできます\n外観の変更 機能\n画面の外観をダーク/ライト/システム設定から変えることができます(システム設定の場合、メニューバーへの反映は再起動後となります)\nテーマ機能\nメニューバーからテーマエディタを開き、ボタン等の色を変えることができます\n修正\nメニューバーのコマンドのカテゴリ分け\nメニューバーにGitHub、YouTube、ニコニコ動画を開く リンクを追加\nアンインストール時に確認ダイアログが出るように\n', 'yt-dlp_GUI v2.1.3': '修正\n音声ダウンロードがオフ、拡張子wav、サムネイルオンの時に音声ダウンロードをオンにしてもサムネイル埋め込みのチェックが外れない問題\n', 'yt-dlp_GUI v2.1.2': '修正\nアンインストール時にconfig.iniが削除されない問題\n', 'yt-dlp_GUI v2.1.1': '修正\nライトモード時に編集ボタンが見えなくなる問題\n「音声のみダウンロード」を選択していない場合にwavファイルになっているとサムネイル埋め込 みを選択できない問題\n', 'yt-dlp_GUI v2.1.0': '機能追加\n音声のみダウンロード時の拡張子選択機能\nmp4、wav、m4a、opusから選べます(wav選択時はサムネイル埋め込みは使えません)\nアンインストール機能\nメニューバーにアプリをアンインストールするボタンを追加しました\n修正\nメニューバーの見た目・動作の改善\nアップデート 通知にて、ダウンロードまたはGitHubへを押したときにアプリが終了するように\nconfig.iniに存在しないキーを要求したときにキーを生成するように\n新しいバージョンダウンロード時に前バージョンの設定を引き継げます\nダウンロード時にエラーが発生した場合にエラーメッセージのダイアログが出るように\nエラーの種類によるメッセージの変更は今後行うつもりです\n', 'yt-dlp_GUI v2.0.3': '修正\nファイル名テンプレートの"FPS"が変換できていなかったのを修正\n', 'yt-dlp_GUI v2.0.2': '機能追加\n ファイル名テンプレートの作成機能\nファイル名入力欄左のボタンを押すとテンプレートの作成ができるウィンドウが開きます。動画のタイトルやID、作者などを自動で設定することができます。\n修正\n保存先フォルダを手入力したときにconfig.iniに書き込まれない問題を修正\n', 'yt-dlp_GUI v2.0.1': '機能追加\n最新バージョン通知\n新 しいバージョンがあると起動したときに案内が出る\n', 'yt-dlp_GUI v2.0.0': '機能追加\nアプリをポータブル形式からインストーラ形式に変更\nexeファイルを実行するとPCにインストールされます\n音声のみダウンロード(mp3)、サムネイルの埋め込み機能を実装\nこのオプションはアプリを閉じても保存されます\nアイコンの設定（変わるか もしれません）\n修正\nウィンドウサイズを変えた時に各ウィジェットが追従するように変更\n', 'yt-dlp_GUI v1.2.1': '機能追加\nメニューバーの追加\nウィンドウ上部 にメニューバーを追加\n「開く」からYouTubeのリンクを開くことができる\nその他\nffmpegを同梱したので、ffmpegをインストールしていない人でも使用できます\n', 'yt-dlp_GUI v1.2.0': '機能追加\nプログレスバーの実装\nダウンロード時の進捗、ファイル容量、ダウンロード速度、残り時間を表示するように\n修正\nダウンロード時にGUI がフリーズする不具合の修正\nアプリを起動したときに前回最後に開いたフォルダを自動で保存先に入力するように\nダウンロード完了の通知をダイアログからWindowsの通 知へ変更\n', 'yt-dlp_GUI v1.1.0': '修正\nsubprocessからPythonライブラリyt_dlpの使用に変更\n※yt-dlpのダウンロード無しに使用できます\n', 'yt-dlp_GUI v1.0.1': '修正\nテキストボックス内のテキストが間違っていたのを修正\n', 'yt-dlp_GUI v1.0': '機能追加\n基本的なダウンロード機能の追加(現在最高画質のみ)\n'}`

**Comment by clay7614** [comment]
ちょっとここまだいろいろ弄ってるので少し時間かかるかも

**Comment by clay7614** [comment]
main.pyの中に関数を組み込んでおいたので、プルリクしておきます。

**Comment by okata-t** [comment]
次何か機能を作ったときに合わせてリリースします
