### ISSUE TITLE
動画情報の取得機能について

### ISSUE THREAD

**Issue by clay7614** [okata-t/yt-dlp_GUI#32]
ウィンドウサイズが大きく変化するようなウィジェットの動的変化を行うよりは、動画情報の取得前から予め適当な画像と時間指定関連のウィジェットを表示させといた方がいいと思います。

**Comment by okata-t** [comment]
これに関してはこの機能を普段使わない場合に場所を取る範囲が広いと邪魔かと思って選択時拡張するという方法を取りました
僕的には画面右側のオプションが増えたら常時表示にしようかと思っています

**Comment by clay7614** [comment]
回答ありがとうございます。
納得しました、その計画で良いと思います。
